# -*- coding: utf-8 -*-
"""Amber-RAG-LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Fh65HzgYs5qz8nPbOifWpUbsdMHlfI0

# AMBER RAG LLM Support System
"""

from importlib import reload  # Reload modules during development
import os  # OS utilities
import requests  # HTTP requests
import numpy as np  # Numerical operations
import faiss  # Vector similarity search

import database  # Local database module
from database import AmberChromaAPI  # Amber-Chroma interface

from pypdf import PdfReader  # PDF reading
from sentence_transformers import SentenceTransformer  # Text embeddings

from datetime import datetime  # Date parsing and formatting

reload(database)  # Refresh module changes

# Chroma DB instance
API_CHROMA_DB = AmberChromaAPI(db_path="/opt/chromadb/data/amber_chroma_db")
# Embedding model
EMBEDDER = SentenceTransformer("all-MiniLM-L6-v2")
# PDF file path
PDF_ADDRESS = "Amber25.pdf"
# Local Ollama server URL
OLLAMA_URL = "http://127.0.0.1:11434"

threshold_ChromaDB = 0.40 # Similarity threshold for Mails
threshold_PDF = 0.45  # Similarity threshold for PDF results

# --------------------------------------------------------
#                        CHUNKING
# --------------------------------------------------------
def chunk_text(text, size=700, overlap=100):
    """
    Splits long text into overlapping chunks.

    Parameters:
        text (str): Full document text.
        size (int): Maximum characters per chunk.
        overlap (int): Number of overlapping characters between chunks.

    Returns:
        list[str]: List of text chunks.
    """
    # Store generated chunks
    chunks = []

    # Step size to maintain overlap
    step = size - overlap

    # Iterate over text using sliding window
    for i in range(0, len(text), step):
        # Extract chunk of fixed size
        chunk = text[i:i + size]
        # Skip empty/whitespace chunks
        if chunk.strip():
            chunks.append(chunk)

    # Return all chunks
    return chunks


# --------------------------------------------------------
#                        FAISS
# --------------------------------------------------------
def build_or_load_index(pdf_path, chunk_size=700, overlap=100):
    """
    Builds a FAISS vector index from a PDF file or loads an existing one.

    Steps:
    1. Check if FAISS index already exists.
    2. If yes → load index and chunks.
    3. If no → extract text from PDF.
    4. Chunk text into overlapping pieces.
    5. Generate embeddings.
    6. Normalize embeddings for cosine similarity.
    7. Build FAISS index and save to disk.

    Returns:
        index (faiss.Index): FAISS search index.
        chunks (list[str]): Corresponding text chunks.
    """

    # Remove .pdf extension
    base_name = os.path.splitext(pdf_path)[0]
    # Path to saved FAISS index
    index_path = base_name + ".faiss"
    # Path to saved chunks
    chunks_path = base_name + ".chunks.npy"

    if os.path.exists(index_path) and os.path.exists(chunks_path):
        chunks = np.load(chunks_path, allow_pickle=True)

        # Safety check: detect old format (strings)
        if len(chunks) > 0 and isinstance(chunks[0], str):
            print("Old chunk format detected. Rebuilding index...")
        else:
            index = faiss.read_index(index_path)
            return index, chunks

    

    # If no saved index → build new one
    reader = PdfReader(pdf_path)
    # Store extracted text
    text = ""

    # Loop through all pages
    for i, page in enumerate(reader.pages):
        try:
            # Extract page text
            extracted = page.extract_text()
            # Append to full text
            if extracted:
                text += extracted + "\n"
        except Exception:
            print(f"Skipped unreadable page {i}")

    # Split text into overlapping chunks
    # Store chunks WITH metadata
    chunks = []

    for page_num, page in enumerate(reader.pages, start=1):
        try:
            extracted = page.extract_text()
            if not extracted:
                continue

            page_chunks = chunk_text(extracted, chunk_size, overlap)

            for ch in page_chunks:
                chunks.append({
                    "text": ch,
                    "page": page_num,
                    "file": os.path.basename(pdf_path)
                })

        except Exception:
            print(f"Skipped unreadable page {page_num}")

    # Generate embeddings for all chunks
    texts = [c["text"] for c in chunks]

    embeddings = EMBEDDER.encode(
        texts,
        batch_size=32,
        convert_to_numpy=True,
        show_progress_bar=True
    )

    embeddings = np.asarray(embeddings, dtype=np.float32)
    embeddings = np.ascontiguousarray(embeddings)

    # Normalize embeddings for cosine similarity search
    faiss.normalize_L2(embeddings)

    # Get embedding dimension
    dim = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(embeddings)

    # Save index and chunks to disk
    faiss.write_index(index, index_path)
    np.save(chunks_path, chunks)

    return index, chunks



# --------------------------------------------------------
#                        SEARCH
# --------------------------------------------------------
def search_pdf(pdf_path, query, top_k=5, threshold=threshold_PDF):
    """
    Searches a PDF using FAISS similarity search.

    Steps:
    1. Load or build FAISS index.
    2. Embed the query.
    3. Normalize query embedding.
    4. Perform similarity search.
    5. Return top-k most similar chunks.

    Returns:
        list[dict]: List of matching chunks with similarity scores.
    """

    index, chunks = build_or_load_index(pdf_path)

    # Encode query into embedding
    query_embedding = EMBEDDER.encode(
        [query],
        convert_to_numpy=True
    )

    # Normalize for cosine similarity
    query_embedding = np.asarray(query_embedding, dtype=np.float32)
    query_embedding = np.ascontiguousarray(query_embedding)

    faiss.normalize_L2(query_embedding)

    scores, indices = index.search(query_embedding, min(top_k, len(chunks)))

    results = []

    for rank, idx in enumerate(indices[0], 1):
        similarity = float(scores[0][rank - 1])
        chunk = chunks[idx]

        if similarity < threshold:
            continue

        results.append({
            "text": chunk["text"],
            "similarity": similarity,
            "page": chunk["page"],
            "file": chunk["file"]
        })

    return results

# --------------------------------------------------------
#                        PDF RETRIEVAL
# --------------------------------------------------------
def retrieve_with_pdf(question, k_chroma=50, k_pdf=5, threshold=0.2):
    """
    Hybrid retriever: fetches relevant chunks from both ChromaDB and PDF.

    Parameters:
        question (str): User query.
        k_chroma (int): Number of ChromaDB results.
        k_pdf (int): Number of PDF results.
        threshold (float): Minimum similarity threshold for ChromaDB results.

    Returns:
        list[dict]: Sorted list of chunks with similarity and source_type.
    """

    all_chunks = []

    # --- 1) ChromaDB retrieval ---
    chroma_results = retrieve(question, k=k_chroma, threshold=threshold)
    print(f"Retrieved {len(chroma_results)} chunks from ChromaDB")

    for ch in chroma_results:
        # Boost Chroma relevance slightly
        ch["similarity"] = float(ch["similarity"]) + 0.10
        ch["source_type"] = "CHROMA"

    # --- 2) PDF retrieval ---
    pdf_results = []

    if os.path.exists(PDF_ADDRESS):
        raw_pdf_results = search_pdf(PDF_ADDRESS, question, top_k=k_pdf)
        print(f"Retrieved {len(raw_pdf_results)} chunks from PDF")

        for r in raw_pdf_results:
            pdf_results.append({
                "text": r["text"],
                "author": "Amber Manual",
                "subject": r["file"],  # ← file name used here
                "date_iso": "",
                "url": f"file://{PDF_ADDRESS}",
                "page": r["page"],
                "file": r["file"],
                "similarity": float(r["similarity"]) - 0.05,
                "source_type": "PDF"
            })
    else:
        print("PDF not found. Skipping PDF retrieval.")

    # --- 3) Sort each source individually ---
    chroma_sorted = sorted(chroma_results, key=lambda x: x["similarity"], reverse=True)
    pdf_sorted = sorted(pdf_results, key=lambda x: x["similarity"], reverse=True)

    # --- 4) Merge both sources, Chroma first, then PDF ---
    all_chunks = sorted(chroma_sorted + pdf_sorted, key=lambda x: x["similarity"], reverse=True)

    return all_chunks


# --------------------------------------------------------
#                        PROMPT
# --------------------------------------------------------
SYSTEM_PROMPT = """
You are AmberRAG, an expert AI assistant specializing in the AMBER molecular dynamics suite
and AmberTools workflows.

You answer questions strictly using the provided Context (archive discussions and manuals).


CORE RULES-
1) Use ONLY the provided Context.
2) Do NOT use outside knowledge.
3) Do NOT fabricate commands, flags, or technical details.
4) If the Context is insufficient, say so clearly.

SOURCE USAGE PRIORITY-
- Use PDF/manual sources for authoritative technical details
- Use ChromaDB/email sources for:
  - real-world issues
  - errors
  - compatibility problems
  - user-reported behavior

Combine BOTH when possible.

CITATION RULES-
1) Every factual claim MUST include a citation: [CITE n]
2) Use multiple citations when multiple sources support the answer
3) DO NOT rely on a single source if others are relevant
4) Prefer citing DIFFERENT sources when possible (diversity required)
5) If both:
   - PDF/manual sources AND
   - ChromaDB (emails/discussions)
   are available,
   THEN you MUST cite at least ONE from EACH (if relevant)

6) Do NOT skip lower-ranked sources if they contain relevant supporting details
7) Each citation must refer to exactly one source: [CITE n]
8) Do NOT combine citations (no ranges like [CITE 1-3])

STYLE-
- Start with a direct answer
- Then give a concise technical explanation
- Keep it precise and grounded in the Context
- Do NOT repeat metadata (author, subject, etc.)
- Do NOT mention "context" or "sources" explicitly

ANSWER REQUIREMENT-
- Use as many citations as are reasonably supported by the Context
- If only one relevant source exists, citing one is acceptable
- Do NOT omit citations if relevant information is present
- Every technical claim should include a citation when possible

Always output the final answer WITH citations.
"""

# --------------------------------------------------------
#                        CONTEXT
# --------------------------------------------------------
def build_context(chunks, max_chars: int = 9000):
    """
    Builds a single context string from retrieved chunks for LLM input.

    Steps:
    1. Iterate through retrieved chunks (already ranked).
    2. Add citation-style headers for traceability.
    3. Concatenate chunk text with metadata.
    4. Stop when max character limit is reached.
    5. Return a formatted context block.

    Parameters:
        chunks (list[dict]): Retrieved documents with metadata.
        max_chars (int): Maximum total characters allowed.

    Returns:
        str: Combined context string ready for LLM.
    """
    parts, used = [], 0
    counters = {"CHROMA": 0, "PDF": 0}

    for ch in chunks:
        source = ch.get("source_type", "CHROMA").upper()
        counters[source] += 1
        cite_label = f"[{source} {counters[source]}]"

        if source == "PDF":
            link_or_date = ch.get("url", "N/A")
        else:  # CHROMA
            link_or_date = ch.get("date_iso", "N/A")

        header = (
            f"{cite_label} "
            f"SUBJECT={ch['subject']} | "
            f"AUTHOR={ch['author']} | "
            f"{'URL' if source=='PDF' else 'DATE'}={link_or_date} | "
            f"SIM={ch['similarity']:.3f}"
        )

        body = (ch["text"] or "").strip()
        block = header + "\n" + body + "\n"

        if used + len(block) > max_chars:
            break
        parts.append(block)
        used += len(block)

    return "\n\n-----\n\n".join(parts)

# --------------------------------------------------------
#                        CITATIONS
# --------------------------------------------------------
def make_clickable(text, url):
    return f"\033]8;;{url}\033\\{text}\033]8;;\033\\"

def format_date_iso(iso_date):
    """
    Converts ISO date string to 'Mon D YYYY' format.
    Example: '2020-01-07T20:41:25+00:00' → 'Jan 7 2020'
    """
    if not iso_date:
        return "N/A"
    try:
        dt = datetime.fromisoformat(iso_date.replace("Z", "+00:00"))
        return dt.strftime("%b %-d %Y")  # e.g., Jan 7 2020
    except Exception:
        return iso_date  # Return original if parsing fails

def attach_citations(answer, chunks):
    """
    Adds a 'References' section to the LLM output, including both ChromaDB
    and PDF sources. Prevents duplicate references.

    Parameters:
        answer (str): LLM-generated response.
        chunks (list[dict]): Retrieved chunks with metadata.

    Returns:
        str: Response with References section appended.
    """
    seen = set()
    refs = []
    counters = {"CHROMA": 0, "PDF": 0}

    for ch in chunks:
        source = ch.get("source_type", "CHROMA").upper()
        counters[source] += 1
        cite_label = f"[{source} {counters[source]}]"

        key = (ch.get("subject"), ch.get("url"))
        if key in seen:
            continue
        seen.add(key)

        subject = ch.get("subject", "")
        author = ch.get("author", "")

        if source == "PDF":
            file_name = ch.get("file", "Unknown File")
            page = ch.get("page", "N/A")
            refs.append(f"{cite_label} {file_name}, Page {page}")
        else:  # CHROMA
            date = format_date_iso(ch.get("date_iso", "N/A"))
            refs.append(f"{cite_label} {subject} ({author}) - {date}")

    if refs:
        answer += "\n\nReferences:\n" + "\n".join(refs)

    return answer

# --------------------------------------------------------
#                        BUILD PROMPT
# --------------------------------------------------------
def build_prompt(question: str, context: str) -> list:
    """
    Builds a structured chat prompt for a chat-based LLM.

    Steps:
    1. Add system-level instructions (SYSTEM_PROMPT).
    2. Provide retrieved context to ground the answer.
    3. Append the user’s question.
    4. Instruct the model to answer with citations.

    Parameters:
        question (str): User's question.
        context (str): Retrieved contextual information.

    Returns:
        list[dict]: Chat-formatted messages for LLM API.
    """

    return [
        # System message defines assistant behavior
        {"role": "system", "content": SYSTEM_PROMPT},

        # User message contains context + question
        {
            "role": "user",
            "content": (
                f"Context:\n{context}\n\n"
                f"Question: {question}\n\n"
                "Answer"
            )
        }
    ]

def generate_llama(messages, model="llama3", temperature=0.2):
    """
    Sends chat messages to a local LLaMA 3 model via Ollama API.

    Steps:
    1. Convert structured chat messages into a single prompt string.
    2. Format roles explicitly (System/User/Assistant).
    3. Send POST request to Ollama's /api/generate endpoint.
    4. Return the generated response text.

    Parameters:
        messages (list[dict]): Chat-style messages (role + content).
        model (str): Ollama model name.
        temperature (float): Controls randomness of generation.

    Returns:
        str: Model-generated response.
    """

    # Convert chat-style messages into plain text prompt
    prompt = ""

    for msg in messages:
        role = msg["role"]        # Message role (system/user/assistant)
        content = msg["content"]  # Message content

        # Format based on role
        if role == "system":
            prompt += f"System: {content}\n"
        elif role == "user":
            prompt += f"User: {content}\n"
        elif role == "assistant":
            prompt += f"Assistant: {content}\n"

    # Signal the model to generate assistant continuation
    prompt += "Assistant:"

    # Send request to local Ollama server
    response = requests.post(
        f"{OLLAMA_URL}/api/generate",
        json={
            "model": model,          # Model name (e.g., llama3)
            "prompt": prompt,        # Fully constructed prompt
            "temperature": temperature,  # Sampling randomness
            "stream": False          # Disable streaming response
        }
    )

    response.raise_for_status()  # Raise error if request failed

    # Return clean generated response text
    return response.json()["response"].strip()

# --------------------------------------------------------
#                        RETRIEVE
# --------------------------------------------------------
def retrieve(question: str, k: int = 50, threshold: float = 0.2, where=None):

    results = API_CHROMA_DB.query(
        text=question,
        n=k,
        where=where,
        threshold=threshold
    )

    documents = results["documents"]
    metadatas = results["metadatas"]
    scores = results["scores"]

    out = []

    for doc, meta, score in zip(documents, metadatas, scores):
        out.append({
            "text": doc,
            "author": meta.get("author", "Unknown"),
            "subject": meta.get("subject", "(no subject)"),
            "date_iso": meta.get("date_iso", ""),
            "url": meta.get("url", ""),
            "similarity": float(score),
        })

    return out

# --------------------------------------------------------
#                        RAG EXECUTION
# --------------------------------------------------------
# question = input("Question: ")

"""
RAG Pipeline Execution

Steps:
1. Retrieve relevant chunks (ChromaDB + optional PDF).
2. Build structured context for the LLM.
3. Format messages into chat-style prompt.
4. Generate final response using LLaMA (via Ollama).
5. Print the final answer.
"""

# # Retrieve relevant chunks from hybrid retriever
# chunks = retrieve_with_pdf(
#     question,
#     k_chroma=50,     # Number of ChromaDB results
#     k_pdf=5,         # Number of PDF results
#     threshold=threshold_ChromaDB    # Similarity threshold
# )

# print("\n--- TOP CHUNKS ---")
# for i, ch in enumerate(chunks[:5], 1):
#     print(f"{i}. {ch['subject']} | sim={ch['similarity']:.3f}")
#     print(ch["text"][:150])
#     print("----")

# if __name__ == "__main__":
#     # Generate final answer using local LLaMA
#     answer = generate_llama(messages)  # Send prompt to Ollama LLaMA model
#     final_rag_answer = attach_citations(answer, chunks)

#     print(final_rag_answer)

def run_rag(question):
    # Retrieve relevant chunks from hybrid retriever
    chunks = retrieve_with_pdf(
        question,
        k_chroma=50,     # Number of ChromaDB results
        k_pdf=5,         # Number of PDF results
        threshold=threshold_ChromaDB    # Similarity threshold
    )

    # Build LLM-ready context and prompt
    context = build_context(chunks)          # Combine chunks into single context block
    messages = build_prompt(question, context)  # Create chat-style messages

    # Generate final answer using local LLaMA
    answer = generate_llama(messages)  # Send prompt to Ollama LLaMA model
    final_rag_answer = attach_citations(answer, chunks)

    return {
        "answer": final_rag_answer,
        "chunks": chunks
    }