# -*- coding: utf-8 -*-
"""server_rag_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192IJG5wTemiWfwNlzpzcrG3TRLIiLoJi
"""

from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

chroma_client = Chroma(
    persist_directory="/opt/chromadb/data/amber_chroma_db",
    embedding_function=embedding_model
)

def retrieve_context(query, chroma_client, top_k=10):
    results = chroma_client.similarity_search(query, k=top_k)
    context = "\n".join([r.page_content for r in results])
    return context

def build_prompt(query, context):
    prompt = f"""
    Context:
    {context}

    Question:
    {query}

    Answer the question using ONLY the information in Context.

    STRICT OUTPUT RULES:
    - Output only the final answer.
    - Do NOT restate the question.
    - Do NOT invent information.
    - At the end, include a Sources section listing only the cited sources

    Answer:
    """
    return prompt

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

class LlamaLLM:
    def __init__(
        self,
        model_name="meta-llama/Meta-Llama-3.1-8B-Instruct",
        max_new_tokens=300,
        temperature=0.7,
        use_device_map=False,
    ):
        print("Loading tokenizer...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        print("Loading model...")

        if use_device_map:
            device_map = "auto"
        else:
            device_map = 0 if torch.cuda.is_available() else -1

        self.pipe = pipeline(
            "text-generation",
            model=model_name,
            tokenizer=self.tokenizer,
            device=device_map
        )

        self.gen_cfg = {
            "max_new_tokens": max_new_tokens,
            "do_sample": temperature > 0.0,
            "temperature": float(temperature),
            "num_beams": 1 if temperature > 0 else 4,
        }

    def generate_answer(self, prompt: str) -> str:
        output = self.pipe(prompt, **self.gen_cfg)
        return output[0]["generated_text"]

llm = LlamaLLM()

def rag_pipeline(user_query):
    context = retrieve_context(user_query, chroma_client)

    prompt = build_prompt(user_query, context)
    answer = llm.generate_answer(prompt)

    if "Sources:" in final_answer:
        final_answer = final_answer.split("Sources:")[0] + "Sources:" + final_answer.split("Sources:")[1]

    return final_answer

if __name__ == "__main__":
    query = input("Question: ")
    response = rag_pipeline(query)
    print("\nAMBER Support:\n", response)